spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Sejongmate!
#    url: jdbc:mysql://${SEJONGMATE_RDS_URL}:3306/sejongmatedb?serverTimezone=Asia/Seoul
#    username: ${SEJONGMATE_RDS_USER}
#    password: ${SEJONGMATE_RDS_PW}

  jpa:
    hibernate:
      ddl-auto: update 
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    generate-ddl: true

  jwt:
    secret: ${SEJONGMATE_JWT_KEY}
    token:
      access-expiration-time: 43200000    # 12시간
      refresh-expiration-time: 604800000   # 7일


  driver:
    path: chromedriver

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 로그로 sql 파라미터 값 찍어줌
