= Sejongmate API 문서
https://github.com/SejongChatbot/server
:doctype: book
:icons: font
:source-highlighter: highlightjs // 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:toc: left // toc (Table Of Contents)를 문서의 좌측에 두기
:toclevels: 2
:sectlinks:

[[User-API]]
== User API


[[User-회원가입]]
=== User 회원가입
operation::user-signup[snippets='http-request,http-response,response-fields']


[[User-로그인]]
=== User 로그인
operation::user-login[snippets='http-request,http-response,response-fields']


[[User-단일-조회]]
=== User 단일 조회
operation::user-get[snippets='http-request,path-parameters,http-response,response-fields']



[[Chat-API]]
== Chat API


[[Chat-채팅방-생성]]
=== 채팅방 생성
operation::chat-room-post[snippets='http-request,http-response,response-fields']


[[Chat-채팅-생성]]
=== 채팅 생성 (채팅 보내기)
operation::chat-message-post[snippets='http-request,http-response,response-fields']


[[Chat-채팅방-목록-조회]]
=== 채팅방 목록 조회
operation::chat-room-list-get[snippets='http-request,path-parameters,http-response,response-fields']


[[Chat-채팅-목록-조회]]
=== 채팅 목록 조회
operation::chat-room-message-get[snippets='http-request,path-parameters,http-response,response-fields']


[[Chat-채팅방-나가기]]
=== 채팅방 나가기
operation::chat-room-user-delete[snippets='http-request,path-parameters,http-response,response-fields']


[[Post-API]]
== Post API


[[Post-글-생성]]
=== 글 생성
operation::create-post[snippets='http-request,http-response,response-fields']


[[Post-댓글-생성]]
=== 댓글 생성
operation::create-comment[snippets='http-request,http-response,response-fields']


[[Post-스크랩-생성]]
=== 스크랩 생성
operation::create-scrap[snippets='http-request,http-response,response-fields']

[[Post-전체-글-목록-조회]]
=== 전체 글 목록 조회
operation::get-post-list[snippets='http-request,http-response,response-fields']

[[Post-카테고리-별-글-목록-조회]]
=== 카테고리 별 글 목록 조회
operation::get-post-list-by-category[snippets='http-request,path-parameters,http-response,response-fields']

[[Post-카테고리-및-대면여부-별-글-목록-조회]]
=== 카테고리 및 대면여부 별 글 목록 조회
operation::get-post-list-by-category-and-type[snippets='http-request,path-parameters,http-response,response-fields']

[[Post-단일-글-상세-조회]]
=== 단일 글 상세 조회
operation::get-post[snippets='http-request,path-parameters,http-response,response-fields']

[[Post-스크랩-글-목록-조회]]
=== 스크랩 글 목록 조회
operation::get-scraped-post[snippets='http-request,path-parameters,http-response,response-fields']

[[Post-스크랩-삭제]]
=== 스크랩 삭제
operation::delete-scrap[snippets='http-request,path-parameters,http-response,response-fields']


